apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: envoy-data-side-car
  labels:
    app: envoy-data-side-car
spec:
  type: NodePort
  ports:
  - port: 80
    name: envoy-data-side-car
    targetPort: 80
    nodePort: 30080
  - port: 8081
    name: envoy-data-side-car-admin
    targetPort: 8081
    nodePort: 30081
  selector:
    app: envoy-data-side-car
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envoy-data-side-car-deployment
spec:
  template:
    metadata:
      labels:
        app: envoy-data-side-car
    spec:
      containers:
      - name: envoy-data-side-car-container
        image: 190740472821.dkr.ecr.ap-south-1.amazonaws.com/eks_envoy_data_side_car0:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
