apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: front-envoy
  labels:
    app: front-envoy
spec:
  type: NodePort
  ports:
  - port: 80
    name: front-envoy
    targetPort: 80
    nodePort: 30050
  - port: 8001
    name: front-envoy-admin
    targetPort: 8001
    nodePort: 30051
  selector:
    app: front-envoy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-envoy-deployment
spec:
  template:
    metadata:
      labels:
        app: front-envoy
    spec:
      containers:
      - name: front-envoy-container
        image: 190740472821.dkr.ecr.ap-south-1.amazonaws.com/eks_front_proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
