FROM envoyproxy/envoy-alpine:latest

RUN apk update && apk add python3 bash curl bind-tools
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD PaymentService.py /code
ADD StartPaymentService0.sh /usr/local/bin/start_service.sh
ADD service-envoy.yaml /etc/service-envoy.yaml
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
