apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: envoy-payment-side-car1
  labels:
    app: envoy-payment-side-car1
spec:
  type: NodePort
  ports:
  - port: 80
    name: envoy-payment-side-car1
    targetPort: 80
    nodePort: 30110
  - port: 8081
    name: envoy-payment-side-car1-admin
    targetPort: 8081
    nodePort: 30111
  selector:
    app: envoy-payment-side-car1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envoy-payment-side-car1-deployment
spec:
  template:
    metadata:
      labels:
        app: envoy-payment-side-car1
    spec:
      containers:
      - name: envoy-payment-side-car1-container
        image: envoy-payment-side-car1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
